// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctvjjzbttzrpzkjvbcxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0dmpqemJ0dHpycHpranZiY3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTYzMTMsImV4cCI6MjA2NDI3MjMxM30.DFrnNkeMTsP2xNCey-MKE-MpNU4g9bqmRaeccFkZZkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);